version: '3.3'
services:
        webapp:
                image: httpd
                ports: 
                        - 8080:80
                volumes:
                        - ./:/usr/local/apache2/htdocs
